### PR TITLE
Ehub 39 : Hub performance optimisation

### PR DESCRIPTION
**Pull request by AkhileshPrajapatiNV**
All performance & code optimisation items are mentioned in enclosed file .
[EHUB-39 performance analysis summary (1).odt](https://github.com/entando-samples/entando-hub/files/7676437/EHUB-39.performance.analysis.summary.1.odt)

### CODE REVIEW

**Review by nshaw — CHANGES_REQUESTED** [review]
Nice work, looks a lot faster in my local testing. However, I see a fair bit of commented out code with ticket numbers in the comments so that will need to be cleaned up before merging. It was probably already in your plan.

**Comment by AkhileshPrajapatiNV** [comment]
Yes, we will remove commented code first.Thanks

**Review by SACHIN-BAGHEL — APPROVED** [review]

**Comment by AkhileshPrajapatiNV** [comment]
@nshaw We removed the commented code. Changes are tested as well working for us.

**Review by nshaw — APPROVED** [review]

**Comment by nshaw** [comment]
@AkhileshPrajapatiNV very good, thanks!

**Pull request merged**
